#!/usr/bin/env python3
"""
Convert Spleen BDF bitmap fonts into the column-major, 8px-strip byte format
used by IronOS' OLED driver (see OLED::drawArea / drawChar).

A glyph of W x H pixels (H a multiple of 8) is encoded as H/8 strips, each strip
being W bytes (one per column), the LSB of a byte being the top-most pixel of
that 8px strip. This matches the existing font06 (6x8) / font12 (12x16) tables.

This tool is intentionally standalone so the conversion can be sanity-checked by
rendering glyphs back to ASCII art (`--preview`) without needing hardware. A
later step uses `glyph_to_bytes()` to emit C tables.
"""
import argparse
import os
from typing import Optional

from bdflib import reader as bdfreader
from bdflib.model import Font

HERE = os.path.dirname(os.path.abspath(__file__))

# (filename, cell width, cell height, font ascent) for each Spleen size we use.
FONTS = {
    "8x16": ("spleen/spleen-8x16.bdf", 8, 16, 12),
    "12x24": ("spleen/spleen-12x24.bdf", 12, 24, 19),
}


def load_font(path: str) -> Font:
    with open(os.path.join(HERE, path), "rb") as f:
        return bdfreader.read_bdf(f)


def glyph_to_bytes(font: Font, ch: str, dst_w: int, dst_h: int, ascent: int) -> Optional[bytes]:
    """Encode a single character into IronOS column-major strip bytes."""
    try:
        glyph = font[ord(ch)]
    except KeyError:
        return None
    data = glyph.data
    src_left, src_bottom, src_w, src_h = glyph.get_bounding_box()

    # (x, y) are cell coordinates with origin at the top-left of the dst cell.
    def get_cell(x: int, y: int) -> bool:
        adj_x = x - src_left
        if adj_x < 0 or adj_x >= src_w:
            return False
        # Place the glyph using the font baseline: the baseline sits `ascent`
        # rows below the top of the cell, and the bbox bottom is `src_bottom`
        # above the baseline (negative for descenders).
        top_offset = ascent - src_h - src_bottom
        adj_y = y - top_offset
        if adj_y < 0 or adj_y >= src_h:
            return False
        # data is stored bottom row first; LSB is the right-most pixel.
        return bool(data[src_h - adj_y - 1] & (1 << (src_w - adj_x - 1)))

    bs = bytearray()
    for block in range(dst_h // 8):
        for c in range(dst_w):
            b = 0
            for r in range(8):
                if get_cell(c, r + 8 * block):
                    b |= 0x01 << r
            bs.append(b)
    return bytes(bs)


def render_ascii(bs: bytes, dst_w: int, dst_h: int) -> str:
    """Render encoded bytes back to ASCII art to verify the conversion."""
    lines = []
    for y in range(dst_h):
        block = y // 8
        bit = y % 8
        row = []
        for c in range(dst_w):
            byte = bs[block * dst_w + c]
            row.append("##" if (byte >> bit) & 1 else "..")
        lines.append("".join(row))
    return "\n".join(lines)


# Glyph set baked into the C tables: printable ASCII, then the degree sign.
# Index i in the table is (codepoint - 0x20); the degree sign is the last entry.
FIRST_CHAR = 0x20
LAST_CHAR = 0x7E
DEGREE = 0xB0


def charset() -> str:
    return "".join(chr(c) for c in range(FIRST_CHAR, LAST_CHAR + 1)) + chr(DEGREE)


def emit_c_array(name: str, size: str) -> str:
    path, dst_w, dst_h, ascent = FONTS[size]
    font = load_font(path)
    bytes_per_glyph = dst_w * (dst_h // 8)
    lines = [f"const uint8_t {name}[] = {{"]
    for ch in charset():
        bs = glyph_to_bytes(font, ch, dst_w, dst_h, ascent)
        if bs is None:
            print(f"WARNING: {size} missing glyph {ch!r}; emitting blank")
            bs = bytes(bytes_per_glyph)
        label = "DEG" if ord(ch) == DEGREE else (repr(ch)[1:-1] if ch != "\\" else "backslash")
        lines.append("    " + "".join(f"0x{b:02X}, " for b in bs).rstrip() + f" // {label}")
    lines.append("};")
    return "\n".join(lines)


def emit_c(out_dir: str) -> None:
    header = f"""// Generated by Translations/gen_spleen_fonts.py - do not edit by hand.
// Spleen bitmap fonts (Frederic Cambus, BSD 2-Clause) converted to the
// IronOS column-major 8px-strip format. Tables cover printable ASCII
// (0x{FIRST_CHAR:02X}..0x{LAST_CHAR:02X}); the degree sign (0x{DEGREE:02X}) is the final entry.
#ifndef SPLEEN_FONT_H_
#define SPLEEN_FONT_H_
#include <stdint.h>

#define SPLEEN_FIRST_CHAR   0x{FIRST_CHAR:02X}
#define SPLEEN_LAST_CHAR    0x{LAST_CHAR:02X}
#define SPLEEN_DEGREE       0x{DEGREE:02X}
#define SPLEEN_DEGREE_INDEX ({LAST_CHAR} - {FIRST_CHAR} + 1)

#define SPLEEN_8X16_WIDTH   {FONTS['8x16'][1]}
#define SPLEEN_8X16_HEIGHT  {FONTS['8x16'][2]}
#define SPLEEN_12X24_WIDTH  {FONTS['12x24'][1]}
#define SPLEEN_12X24_HEIGHT {FONTS['12x24'][2]}

extern const uint8_t spleen_8x16[];  // (printable ASCII + degree) x {FONTS['8x16'][1] * (FONTS['8x16'][2] // 8)} bytes/glyph
extern const uint8_t spleen_12x24[]; // (printable ASCII + degree) x {FONTS['12x24'][1] * (FONTS['12x24'][2] // 8)} bytes/glyph

#endif /* SPLEEN_FONT_H_ */
"""
    source = (
        "// Generated by Translations/gen_spleen_fonts.py - do not edit by hand.\n"
        '#include "SpleenFont.h"\n\n'
        + emit_c_array("spleen_8x16", "8x16")
        + "\n\n"
        + emit_c_array("spleen_12x24", "12x24")
        + "\n"
    )
    with open(os.path.join(out_dir, "SpleenFont.h"), "w") as f:
        f.write(header)
    with open(os.path.join(out_dir, "SpleenFont.cpp"), "w") as f:
        f.write(source)
    print(f"Wrote SpleenFont.h / SpleenFont.cpp to {out_dir}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--size", choices=sorted(FONTS), default="12x24")
    ap.add_argument("--preview", default="0123456789", help="characters to render as ASCII art")
    ap.add_argument("--emit", metavar="DIR", help="emit SpleenFont.h/.cpp into DIR")
    args = ap.parse_args()

    if args.emit:
        emit_c(args.emit)
        return

    path, dst_w, dst_h, ascent = FONTS[args.size]
    font = load_font(path)
    print(f"# Spleen {args.size} (cell {dst_w}x{dst_h}, ascent {ascent}) -> {dst_w * (dst_h // 8)} bytes/glyph")
    for ch in args.preview:
        bs = glyph_to_bytes(font, ch, dst_w, dst_h, ascent)
        if bs is None:
            print(f"\n[{ch!r}] MISSING")
            continue
        print(f"\n[{ch!r}] ({len(bs)} bytes)")
        print(render_ascii(bs, dst_w, dst_h))


if __name__ == "__main__":
    main()
