// Generated by Translations/gen_spleen_fonts.py - do not edit by hand.
// Spleen bitmap fonts (Frederic Cambus, BSD 2-Clause) converted to the
// IronOS column-major 8px-strip format. Tables cover printable ASCII
// (0x20..0x7E); the degree sign (0xB0) is the final entry.
#ifndef SPLEEN_FONT_H_
#define SPLEEN_FONT_H_
#include <stdint.h>

#define SPLEEN_FIRST_CHAR   0x20
#define SPLEEN_LAST_CHAR    0x7E
#define SPLEEN_DEGREE       0xB0
#define SPLEEN_DEGREE_INDEX (126 - 32 + 1)

#define SPLEEN_8X16_WIDTH   8
#define SPLEEN_8X16_HEIGHT  16
#define SPLEEN_12X24_WIDTH  12
#define SPLEEN_12X24_HEIGHT 24

extern const uint8_t spleen_8x16[];  // (printable ASCII + degree) x 16 bytes/glyph
extern const uint8_t spleen_12x24[]; // (printable ASCII + degree) x 36 bytes/glyph

#endif /* SPLEEN_FONT_H_ */
